### ISSUE TITLE
Clear fix util

### ISSUE THREAD

**Issue by coryrylan** [blueprintui/blueprintui#1]
Need to add utility clearfix class to the grid.

``` css
.clear-fix:after {
    content: "";
    display: table;
    clear: both;
}
```
